AllCops:
  TargetRubyVersion: 2.3

Lint/HandleExceptions:
  Exclude:
    - spec/aws_sns_manager/client_spec.rb

Metrics/LineLength:
  Exclude:
    - aws_sns_manager.gemspec

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
