deploy:
  provider: rubygems
  api_key:
    secure: DaIvbW+6p9LNv3YrnsIDtwo4f/7pIe1Y1E5tQuoOspN+lnUhaL5qFWYtbyuMUW9yG9TQhPCn9irCbUBkoKLCKCcbtYrQsELY2hx+z3fFJ7wZMriLojCttf4yZfGdK539clcPsIpkWVSsDaUnxGC1nbj5pJBLJk4U23SiZrMWL0I=
  gem: aws_sns_manager
  on:
    tags: true
    repo: nafu/aws_sns_manager
addons:
  code_climate:
    repo_token:
      secure: hZdPD3pLNCe7aFaRkEI1plpe16NVacxu6r1GwbngOq/8bWf9EGFH1+KZ/TTT4JyXCki+RrqiD4RybnCQfOTuBD6Lt5q79b1EhygNlnlgbXRzWCmeksurwelRCfYUORTz/Wl+eN9xvP8CpxZ1sO/Y7rVFV3wyDBt0wBR63vRT7ko=
