language: ruby
before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
cache: bundler
rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.9
  - 2.6.10
  - 2.7.6
  - 3.0.4
  - 3.1.2
jobs:
  include:
    - stage: deploy
      rvm: 3.0.4
      deploy:
        provider: rubygems
        api_key:
          secure: DaIvbW+6p9LNv3YrnsIDtwo4f/7pIe1Y1E5tQuoOspN+lnUhaL5qFWYtbyuMUW9yG9TQhPCn9irCbUBkoKLCKCcbtYrQsELY2hx+z3fFJ7wZMriLojCttf4yZfGdK539clcPsIpkWVSsDaUnxGC1nbj5pJBLJk4U23SiZrMWL0I=
        gem: aws_sns_manager
        on:
          tags: true
          repo: nafu/aws_sns_manager
addons:
  code_climate:
    repo_token: f963cfa99b5c830023926cbaa0cf70b2112d28cdc1b7db78bf39841936e4f766
